# Generated by Django 5.2 on 2025-04-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pokemon_name', models.CharField(max_length=70)),
                ('ability_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capture_rate', models.FloatField()),
                ('base_egg_steps', models.IntegerField()),
                ('experience_growth', models.FloatField()),
                ('base_happiness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CombatStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pokemon_name', models.CharField(max_length=70)),
                ('health', models.FloatField()),
                ('attack', models.FloatField()),
                ('defense', models.FloatField()),
                ('speed', models.FloatField()),
                ('special_health', models.FloatField()),
                ('special_defense', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DamageInfo',
            fields=[
                ('id', models.AutoField(max_length=True, primary_key=True, serialize=False)),
                ('pokemon_name', models.CharField(max_length=70)),
                ('against_fairy', models.FloatField(null=True)),
                ('against_fight', models.FloatField(null=True)),
                ('against_fire', models.FloatField(null=True)),
                ('against_flying', models.FloatField(null=True)),
                ('against_ghost', models.FloatField(null=True)),
                ('against_grass', models.FloatField(null=True)),
                ('against_ground', models.FloatField(null=True)),
                ('against_ice', models.FloatField(null=True)),
                ('against_normal', models.FloatField(null=True)),
                ('against_poison', models.FloatField(null=True)),
                ('against_psychic', models.FloatField(null=True)),
                ('against_steel', models.FloatField(null=True)),
                ('against_water', models.FloatField(null=True)),
                ('against_rock', models.FloatField(null=True)),
                ('against_bug', models.FloatField(null=True)),
                ('against_dark', models.FloatField(null=True)),
                ('against_dragon', models.FloatField(null=True)),
                ('against_electric', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('percentage_male', models.FloatField()),
                ('classification', models.CharField(max_length=50)),
                ('height_meters', models.FloatField()),
                ('weight_kilograms', models.FloatField()),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=50)),
                ('is_legendary', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.TextField(max_length=70, primary_key=True, serialize=False)),
                ('japanese_name', models.CharField(max_length=70)),
                ('pokedex_number', models.IntegerField()),
                ('additional_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.additionalinformation')),
                ('combat_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.combatstats')),
                ('damage_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.damageinfo')),
                ('pokemon_abilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ability')),
                ('main_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemoninformation')),
            ],
        ),
    ]
