# Generated by Django 5.2 on 2025-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_special_health_combatstats_special_attack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_abilities',
        ),
    ]
