# Generated by Django 5.2 on 2025-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pokemon_pokemon_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninformation',
            name='height_meters',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='weight_kilograms',
            field=models.FloatField(blank=True),
        ),
    ]
