# Generated by Django 5.2 on 2025-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pokemoninformation_height_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninformation',
            name='height_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='weight_kilograms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
