# Generated by Django 5.2 on 2025-04-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pokemoninformation_height_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ability',
            name='pokemon_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='combatstats',
            name='pokemon_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='damageinfo',
            name='pokemon_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='japanese_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.TextField(max_length=90, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='classification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='generation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='type1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemoninformation',
            name='type2',
            field=models.CharField(max_length=200),
        ),
    ]
