# Generated by Django 5.2 on 2025-04-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ability_ability_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='pokemon_name',
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
            ],
        ),
    ]
