# Generated by Django 5.2 on 2025-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ability_pokemon_name_pokemonability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='capture_rate',
            field=models.CharField(max_length=100),
        ),
    ]
